model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "inpaint"
    cond_stage_key: "image"
    image_size: 64
    channels: 5
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: train/loss
    u_cond_percent: 0.2
    scale_factor: 0.18215
    use_ema: False

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 18
        out_channels: 5
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: [768]
        use_checkpoint: True
        legacy: False
        add_conv_in_front_of_unet: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
      batch_size: 10
      wrap: False
      train:
          target: ldm.data.dataset_VITONHD.try_on_dataset_VITONHD
          params:
              state: train
              dataset_dir: datasets/VITONHD
              order: paired
              image_size: 224
      validation:
          target: ldm.data.dataset_VITONHD.try_on_dataset_VITONHD
          params:
              state: validation
              dataset_dir: datasets/VITONHD
              order: unpaired
              image_size: 224
      test:
          target: ldm.data.dataset_VITONHD.try_on_dataset_VITONHD
          params:
              state: test
              dataset_dir: datasets/VITONHD
              order: paired
              image_size: 224

lightning:
  trainer:
    max_epochs: 80
    num_nodes: 1
    accelerator: 'gpu'
    gpus: "0"
    limit_val_batches: 0.5
    check_val_every_n_epoch: 10